# Proprocesammiento

En esta notebook se hace lo siguiente:  
1.- se calcula la Mean de los features que tiene valores nulos para luego ser imputados.  
2.- Se elimina las variables categoricas.  
3.- se cacula en Z-score para eliminar los Outliers.  
4.- Se caclula en valor VIF para ser usado para eliminas las variables multicolineares.  
5.- Se determinan y corrigen los feautures Skewed.  
6.- Se estandarizan las columnas usando un StandardScaler.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
df_full = pd.read_csv('../../data/raw/train_dataset.csv')

In [7]:
# Se obtienen los valores de la Mean antes de imputar para poder imputar la misma media en ambos set de datos
a = df_full['year_built'].mean()
b = df_full['energy_star_rating'].mean()
c = df_full['direction_max_wind_speed'].mean()
d = df_full['direction_peak_wind_speed'].mean()
e = df_full['max_wind_speed'].mean()
f = df_full['days_with_fog'].mean()

In [8]:
df_full['year_built'].fillna(a, inplace=True)
df_full['energy_star_rating'].fillna(b, inplace=True)
df_full['direction_max_wind_speed'].fillna(c, inplace=True)
df_full['direction_peak_wind_speed'].fillna(d, inplace=True)
df_full['max_wind_speed'].fillna(e, inplace=True)
df_full['days_with_fog'].fillna(f, inplace=True)

In [9]:
df_full['State_Factor'].value_counts()

State_6     50840
State_11     6412
State_1      5618
State_2      4871
State_4      4300
State_8      3701
State_10       15
Name: State_Factor, dtype: int64

In [10]:
df_full['building_class'].value_counts()

Residential    43558
Commercial     32199
Name: building_class, dtype: int64

In [11]:
df_full.head()

,Year_Factor,State_Factor,building_class,facility_type,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,id
0,1,State_1,Commercial,Grocery_store_or_food_market,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,248.682615,0
1,1,State_1,Commercial,Warehouse_Distribution_or_Shipping_center,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,26.500150,1
2,1,State_1,Commercial,Retail_Enclosed_mall,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,24.693619,2
3,1,State_1,Commercial,Education_Other_classroom,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,48.406926,3
4,1,State_1,Commercial,Warehouse_Nonrefrigerated,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,3.899395,4

In [12]:
df_full = df_full.drop(columns=['facility_type', 'id'])

In [13]:
df_full.head()

,Year_Factor,State_Factor,building_class,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui
0,1,State_1,Commercial,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,248.682615
1,1,State_1,Commercial,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,26.500150
2,1,State_1,Commercial,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,24.693619
3,1,State_1,Commercial,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,48.406926
4,1,State_1,Commercial,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,3.899395

In [14]:
df_full.shape

(75757, 62)

In [15]:
ohc = OneHotEncoder()
ohs1 = ohc.fit_transform(df_full.building_class.values.reshape(-1,1)).toarray()
dfs1 = pd.DataFrame(ohs1, columns = ["Temp_building_class_"+str(ohc.categories_[0][i])
                               for i in range(len(ohc.categories_[0]))])
df_full = pd.concat([df_full, dfs1], axis = 1)  
df_full.head()

,Year_Factor,State_Factor,building_class,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,Temp_building_class_Commercial,Temp_building_class_Residential
0,1,State_1,Commercial,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,248.682615,1.0,0.0
1,1,State_1,Commercial,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,26.500150,1.0,0.0
2,1,State_1,Commercial,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,24.693619,1.0,0.0
3,1,State_1,Commercial,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,48.406926,1.0,0.0
4,1,State_1,Commercial,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,3.899395,1.0,0.0

In [16]:
df_full.shape

(75757, 64)

In [17]:
df_full = df_full.drop(columns=['building_class'], axis = 1)
df_full.head()

,Year_Factor,State_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,Temp_building_class_Commercial,Temp_building_class_Residential
0,1,State_1,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,248.682615,1.0,0.0
1,1,State_1,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,26.500150,1.0,0.0
2,1,State_1,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,24.693619,1.0,0.0
3,1,State_1,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,48.406926,1.0,0.0
4,1,State_1,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,3.899395,1.0,0.0

In [18]:
df_full.shape

(75757, 63)

In [19]:
df_full['TEMP_State_Factor']=LabelEncoder().fit_transform(df_full.State_Factor)

In [20]:
df_full.head()

,Year_Factor,State_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,Temp_building_class_Commercial,Temp_building_class_Residential,TEMP_State_Factor
0,1,State_1,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,248.682615,1.0,0.0,0
1,1,State_1,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,26.500150,1.0,0.0,0
2,1,State_1,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,24.693619,1.0,0.0,0
3,1,State_1,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,48.406926,1.0,0.0,0
4,1,State_1,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,3.899395,1.0,0.0,0

In [21]:
df_full = df_full.drop(columns=['State_Factor'], axis = 1)
df_full.head()

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,site_eui,Temp_building_class_Commercial,Temp_building_class_Residential,TEMP_State_Factor
0,1,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,248.682615,1.0,0.0,0
1,1,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,26.500150,1.0,0.0,0
2,1,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,24.693619,1.0,0.0,0
3,1,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,48.406926,1.0,0.0,0
4,1,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,3.899395,1.0,0.0,0

In [22]:
aux_site_eui= pd.DataFrame(df_full['site_eui'])
aux_site_eui.head()

     site_eui
0  248.682615
1   26.500150
2   24.693619
3   48.406926
4    3.899395

In [23]:
df_full = df_full.drop(columns=['site_eui'], axis = 1)
df_full.head()

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,Temp_building_class_Commercial,Temp_building_class_Residential,TEMP_State_Factor
0,1,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,1.0,0.0,0
1,1,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0
2,1,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0
3,1,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0
4,1,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,1.0,0.0,0

In [24]:
df_full.shape

(75757, 62)

In [25]:
df_full = pd.concat([df_full, aux_site_eui], axis = 1)  
df_full.head()

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,Temp_building_class_Commercial,Temp_building_class_Residential,TEMP_State_Factor,site_eui
0,1,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,1.0,0.0,0,248.682615
1,1,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0,26.500150
2,1,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0,24.693619
3,1,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0,48.406926
4,1,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,1.0,0.0,0,3.899395

In [26]:
df_full.shape

(75757, 63)

Se calcula el Z-score para eliminar los outliers

In [27]:
from scipy import stats
import numpy as np

In [28]:
z = np.abs(stats.zscore(df_full))

In [29]:
df_full.shape

(75757, 63)

In [30]:
df_full.head()

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,Temp_building_class_Commercial,Temp_building_class_Residential,TEMP_State_Factor,site_eui
0,1,61242.0,1942.0,11.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,1.0,0.0,0,248.682615
1,1,274000.0,1955.0,45.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0,26.500150
2,1,280025.0,1951.0,97.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0,24.693619
3,1,55325.0,1980.0,46.0,1.8,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,62.779974,1.0,12.000000,1.0,0.0,0,48.406926
4,1,66000.0,1985.0,100.0,2.4,36,50.5,68,35,50.589286,73,40,53.693548,80,41,55.5,78,46,56.854839,84,50,60.5,90,52,62.725806,84,52,62.16129,85,52,64.65,90,47,63.016129,83,43,53.8,72,36,49.274194,71,115,2960,16.59,0.0,0,56.972603,0,0,0,0,14,0,0,0,1.0,1.000000,1.0,109.142051,1.0,0.0,0,3.899395

Se elimina aquellas fillas que no cumplan con el treshold

In [47]:
df_full_z_scores = df_full[(z < 3).all(axis=1)]

In [48]:
df_full_z_scores.shape

(55844, 63)

df_full_SC = df_full_z_scores.drop(columns=['direction_max_wind_speed','direction_peak_wind_speed', 
                                          'max_wind_speed', 'cooling_degree_days','august_avg_temp',
                                          'january_avg_temp','days_below_20F', 'july_avg_temp', 
                                          'days_below_30F','march_min_temp', 'february_avg_temp', 'heating_degree_days',
                                          'days_below_10F','february_min_temp'])

In [46]:
df_full_z_scores.head()

,Year_Factor,floor_area,year_built,energy_star_rating,ELEVATION,january_min_temp,january_avg_temp,january_max_temp,february_min_temp,february_avg_temp,february_max_temp,march_min_temp,march_avg_temp,march_max_temp,april_min_temp,april_avg_temp,april_max_temp,may_min_temp,may_avg_temp,may_max_temp,june_min_temp,june_avg_temp,june_max_temp,july_min_temp,july_avg_temp,july_max_temp,august_min_temp,august_avg_temp,august_max_temp,september_min_temp,september_avg_temp,SKW_days_with_fog,SKW_cooling_degree_days,SKW_june_avg_temp,SKW_july_avg_temp,september_max_temp,october_min_temp,october_avg_temp,october_max_temp,november_min_temp,november_avg_temp,november_max_temp,december_min_temp,december_avg_temp,december_max_temp,cooling_degree_days,heating_degree_days,precipitation_inches,snowfall_inches,snowdepth_inches,avg_temp,days_below_30F,days_below_20F,days_below_10F,days_below_0F,days_above_80F,days_above_90F,days_above_100F,days_above_110F,direction_max_wind_speed,direction_peak_wind_speed,max_wind_speed,days_with_fog,Temp_building_class_Commercial,Temp_building_class_Residential,TEMP_State_Factor,site_eui
1005,2,5112.0,1952.306764,61.048605,116.7,29,51.870968,72,37,53.696429,77,39,54.306452,73,39,59.116667,86,46,62.032258,87,50,65.150000,94,55,66.548387,86,56,66.870968,85,51,64.65,897960.974253,1.928455e+06,1.623023e+27,5.897615e+44,86,48,64.516129,95,39,57.566667,83,33,50.725806,69,321,2135,13.10,0.0,0,59.783562,1,0,0,0,29,3,0,0,66.552675,62.779974,4.190601,109.142051,1.0,0.0,0,88.204070
1047,3,39817.0,1952.306764,61.048605,209.1,21,42.596774,63,26,43.750000,63,32,53.500000,78,33,54.900000,81,41,59.822581,87,50,70.866667,99,59,75.645161,93,55,73.370968,93,41,68.40,897960.974253,3.895078e+07,6.058020e+27,1.513393e+46,92,34,56.725806,78,33,51.233333,73,27,46.564516,68,986,3378,16.07,16.0,18,58.197260,16,0,0,0,87,18,0,0,66.552675,62.779974,4.190601,109.142051,1.0,0.0,0,23.918058
1048,3,153088.0,1952.306764,61.048605,209.1,21,42.596774,63,26,43.750000,63,32,53.500000,78,33,54.900000,81,41,59.822581,87,50,70.866667,99,59,75.645161,93,55,73.370968,93,41,68.40,897960.974253,3.895078e+07,6.058020e+27,1.513393e+46,92,34,56.725806,78,33,51.233333,73,27,46.564516,68,986,3378,16.07,16.0,18,58.197260,16,0,0,0,87,18,0,0,66.552675,62.779974,4.190601,109.142051,1.0,0.0,0,46.341562
1050,3,5478.0,1952.306764,61.048605,73.8,21,42.596774,63,26,43.750000,63,32,53.500000,78,33,54.900000,81,41,59.822581,87,50,70.866667,99,59,75.645161,93,55,73.370968,93,41,68.40,897960.974253,3.895078e+07,6.058020e+27,1.513393e+46,92,34,56.725806,78,33,51.233333,73,27,46.564516,68,986,3378,16.07,16.0,18,58.197260,16,0,0,0,87,18,0,0,66.552675,62.779974,4.190601,109.142051,1.0,0.0,0,127.576434
1051,3,49399.0,1952.306764,61.048605,73.8,21,42.596774,63,26,43.750000,63,32,53.500000,78,33,54.900000,81,41,59.822581,87,50,70.866667,99,59,75.645161,93,55,73.370968,93,41,68.40,897960.974253,3.895078e+07,6.058020e+27,1.513393e+46,92,34,56.725806,78,33,51.233333,73,27,46.564516,68,986,3378,16.07,16.0,18,58.197260,16,0,0,0,87,18,0,0,66.552675,62.779974,4.190601,109.142051,1.0,0.0,0,46.110646

Se verifica para eliminar Skewnes

In [41]:
num_feats = df_full_z_scores.dtypes[df_full_z_scores.dtypes!='object'].index
skew_feats = df_full_z_scores[num_feats].skew().sort_values(ascending= True)
Skewnes = pd.DataFrame({'skew':skew_feats})

In [42]:
print(Skewnes)

                                      skew
july_avg_temp                    -2.195561
june_avg_temp                    -1.962634
cooling_degree_days              -1.731397
days_with_fog                    -1.718110
TEMP_State_Factor                -1.642285
july_min_temp                    -1.608009
august_min_temp                  -1.597283
september_max_temp               -1.559232
february_max_temp                -1.259324
may_max_temp                     -1.133798
september_avg_temp               -1.103220
days_above_80F                   -0.945591
august_avg_temp                  -0.931653
october_min_temp                 -0.899968
july_max_temp                    -0.890228
september_min_temp               -0.853845
october_avg_temp                 -0.851309
january_max_temp                 -0.765358
Temp_building_class_Residential  -0.707525
energy_star_rating               -0.664602
march_min_temp                   -0.514298
october_max_temp                 -0.505606
avg_temp                         -0.473492
may_min_temp                     -0.417419
snowfall_inches                  -0.415525
june_min_temp                    -0.389672
november_max_temp                -0.337834
Year_Factor                      -0.311510
march_max_temp                   -0.196103
december_max_temp                -0.155953
april_min_temp                   -0.144127
days_below_30F                   -0.081673
march_avg_temp                   -0.048612
november_min_temp                -0.004472
days_above_110F                   0.000000
heating_degree_days               0.027918
february_avg_temp                 0.028961
april_avg_temp                    0.055692
year_built                        0.236716
december_min_temp                 0.268103
may_avg_temp                      0.338775
days_below_20F                    0.421906
november_avg_temp                 0.454396
april_max_temp                    0.459119
june_max_temp                     0.483637
august_max_temp                   0.556754
february_min_temp                 0.571444
days_above_90F                    0.649391
precipitation_inches              0.669346
Temp_building_class_Commercial    0.707525
january_avg_temp                  0.785589
site_eui                          0.955612
days_below_10F                    0.969602
snowdepth_inches                  0.974136
days_below_0F                     1.294678
january_min_temp                  1.487223
december_avg_temp                 1.517196
max_wind_speed                    2.073921
floor_area                        2.665256
direction_max_wind_speed          2.884655
ELEVATION                         2.923580
direction_peak_wind_speed         3.126616
days_above_100F                  54.039371

Se trataran con BoxCox solo aquellos features cuyo skew ste por encima de 0.5 y -0.5

In [49]:
df_full_z_scores.insert (31, 'SKW_july_avg_temp', stats.boxcox(df_full_z_scores['july_avg_temp'])[0])
df_full_z_scores.insert (31, 'SKW_june_avg_temp', stats.boxcox(df_full_z_scores['june_avg_temp'])[0])
df_full_z_scores.insert (31, 'SKW_cooling_degree_days', stats.boxcox(df_full_z_scores['cooling_degree_days'])[0])
df_full_z_scores.insert (31, 'SKW_days_with_fog', stats.boxcox(df_full_z_scores['days_with_fog'])[0])
#df_full_z_scores.insert (31, 'SKW_TEMP_State_Factor', stats.boxcox(df_full_z_scores['TEMP_State_Factor'])[0])
df_full_z_scores.insert (31, 'SKW_july_min_temp', stats.boxcox(df_full_z_scores['july_min_temp'])[0])
df_full_z_scores.insert (31, 'SKW_august_min_temp', stats.boxcox(df_full_z_scores['august_min_temp'])[0])
df_full_z_scores.insert (31, 'SKW_september_max_temp', stats.boxcox(df_full_z_scores['september_max_temp'])[0])
df_full_z_scores.insert (31, 'SKW_february_max_temp', stats.boxcox(df_full_z_scores['february_max_temp'])[0])
df_full_z_scores.insert (31, 'SKW_may_max_temp', stats.boxcox(df_full_z_scores['may_max_temp'])[0])
df_full_z_scores.insert (31, 'SKW_september_avg_temp', stats.boxcox(df_full_z_scores['september_avg_temp'])[0])
df_full_z_scores.insert (31, 'SKW_days_above_80F', stats.boxcox(df_full_z_scores['days_above_80F'])[0])
df_full_z_scores.insert (31, 'SKW_august_avg_temp', stats.boxcox(df_full_z_scores['august_avg_temp'])[0])
df_full_z_scores.insert (31, 'SKW_october_min_temp', stats.boxcox(df_full_z_scores['october_min_temp'])[0])
df_full_z_scores.insert (31, 'SKW_july_max_temp', stats.boxcox(df_full_z_scores['july_max_temp'])[0])
df_full_z_scores.insert (31, 'SKW_september_min_temp', stats.boxcox(df_full_z_scores['september_min_temp'])[0])
df_full_z_scores.insert (31, 'SKW_october_avg_temp', stats.boxcox(df_full_z_scores['october_avg_temp'])[0])
df_full_z_scores.insert (31, 'SKW_january_max_temp', stats.boxcox(df_full_z_scores['january_max_temp'])[0])
df_full_z_scores.insert (31, 'SKW_Temp_building_class_Residential', stats.boxcox(df_full_z_scores['Temp_building_class_Residential'])[0])
df_full_z_scores.insert (31, 'SKW_energy_star_rating', stats.boxcox(df_full_z_scores['energy_star_rating'])[0])
df_full_z_scores.insert (31, 'SKW_march_min_temp', stats.boxcox(df_full_z_scores['march_min_temp'])[0])
df_full_z_scores.insert (31, 'SKW_october_max_temp', stats.boxcox(df_full_z_scores['october_max_temp'])[0])
df_full_z_scores.insert (31, 'SKW_august_max_temp', stats.boxcox(df_full_z_scores['august_max_temp'])[0])
df_full_z_scores.insert (31, 'SKW_february_min_temp', stats.boxcox(df_full_z_scores['february_min_temp'])[0])
df_full_z_scores.insert (31, 'SKW_days_above_90F', stats.boxcox(df_full_z_scores['days_above_90F'])[0])
df_full_z_scores.insert (31, 'SKW_precipitation_inches', stats.boxcox(df_full_z_scores['precipitation_inches'])[0])
df_full_z_scores.insert (31, 'SKW_Temp_building_class_Commercial', stats.boxcox(df_full_z_scores['Temp_building_class_Commercial'])[0])
df_full_z_scores.insert (31, 'SKW_january_avg_temp', stats.boxcox(df_full_z_scores['january_avg_temp'])[0])
df_full_z_scores.insert (31, 'SKW_site_eui', stats.boxcox(df_full_z_scores['site_eui'])[0])
df_full_z_scores.insert (31, 'SKW_days_below_10F', stats.boxcox(df_full_z_scores['days_below_10F'])[0])
df_full_z_scores.insert (31, 'SKW_snowdepth_inches', stats.boxcox(df_full_z_scores['snowdepth_inches'])[0])
df_full_z_scores.insert (31, 'SKW_days_below_0F', stats.boxcox(df_full_z_scores['days_below_0F'])[0])
df_full_z_scores.insert (31, 'SKW_january_min_temp', stats.boxcox(df_full_z_scores['january_min_temp'])[0])
df_full_z_scores.insert (31, 'SKW_december_avg_temp', stats.boxcox(df_full_z_scores['december_avg_temp'])[0])
df_full_z_scores.insert (31, 'SKW_max_wind_speed', stats.boxcox(df_full_z_scores['max_wind_speed'])[0])
df_full_z_scores.insert (31, 'SKW_floor_area', stats.boxcox(df_full_z_scores['floor_area'])[0])
df_full_z_scores.insert (31, 'SKW_direction_max_wind_speed', stats.boxcox(df_full_z_scores['direction_max_wind_speed'])[0])
df_full_z_scores.insert (31, 'SKW_ELEVATION', stats.boxcox(df_full_z_scores['ELEVATION'])[0])
df_full_z_scores.insert (31, 'SKW_direction_peak_wind_speed', stats.boxcox(df_full_z_scores['direction_peak_wind_speed'])[0])
df_full_z_scores.insert (31, 'SKW_days_above_100F', stats.boxcox(df_full_z_scores['days_above_100F'])[0])

ValueError: Data must be positive.

In [ ]:
df_full_SKW = df_full_SC.drop(columns=['june_avg_temp','days_with_fog', 
                                          'july_min_temp', 'august_min_temp','september_max_temp',
                                          'february_max_temp','may_max_temp', 'september_avg_temp', 
                                          'august_max_temp','days_above_90F', 'precipitation_inches', 
                                          'december_avg_temp','floor_area','ELEVATION'])

In [ ]:
df_full_SKW.shape

Probamos haciendo una standarizacion normal comun y corriente ya que en teoria se eliminaron los outlier

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
transformer = StandardScaler().fit(df_full_SKW)
df_full_scaled = transformer.transform(df_full_SKW)

In [ ]:
#se debe transforma a un dataframe ya que el metodo transorm lo retorna en un ndarray
df_full_scaled_df = pd.DataFrame(df_full_scaled, columns=df_full_SKW.columns)
df_full_scaled_df.describe()

In [ ]:
df_full_scaled_df.shape

In [ ]:
# Usaremps PCA

aux = df_full_scaled_df.drop(columns=['site_eui'])

pca = PCA().fit(aux)

plt.rcParams["figure.figsize"] = (12,6)

fig, ax = plt.subplots()
xi = np.arange(1, 49, step=1)
y = np.cumsum(pca.explained_variance_ratio_)

plt.ylim(0.0,1.1)
plt.plot(xi, y, marker='o', linestyle='--', color='b')

plt.xlabel('Number of Components')
plt.xticks(np.arange(0, 11, step=1)) #change from 0-based array index to 1-based human-readable label
plt.ylabel('Cumulative variance (%)')
plt.title('The number of components needed to explain variance')

plt.axhline(y=0.95, color='r', linestyle='-')
plt.text(0.5, 0.85, '95% cut-off threshold', color = 'red', fontsize=16)

ax.grid(axis='x')
plt.show()

In [ ]:
df_full_scaled_df.to_csv('data/preprocesada/Full_Data_sin_MultiC_sin_Skew.csv')